# This is for the local ARGO on the Hub
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-clusters-1
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: all-openshift-clusters
    namespace: openshift-gitops

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSet
metadata:
  name: all-openshift-clusters
spec: {}

# This is the ManagedClusterSetBinding to the openshift-gitops namespace
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  clusterSet: all-openshift-clusters

#This is the placement resource for targeting Managed Clusters for
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  #numberOfClusters: 6
  clusterSets:
  - all-clusters
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        # - key: usage
        #   operator: "In"
        #   values:
        #   - production
        #   - development
        - key: vendor
          operator: "In"
          values:
          - OpenShift        